apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: new-nginx
    type: canary
  name: new-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: new-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: new-nginx
        type: canary
    spec:
      volumes:
        - name: canary-volume
          configMap:
            name: canary
      containers:
      - image: nginx:latest
        name: nginx
        resources: {}
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: canary-volume

