apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app1
  name: app1
  namespace: ns1
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 80
  selector:
    app: app1
status:
  loadBalancer: {}
