apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app2
  name: app2
  namespace: ns2
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 80
  selector:
    app: app2
status:
  loadBalancer: {}
