apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-06-26T20:28:06Z"
  generation: 1
  labels:
    app: myweb
  name: myweb
  namespace: default
  resourceVersion: "135510"
  uid: 95058531-1bec-4c8a-841b-5c20138d56a0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: myweb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myweb
    spec:
      volumes:
        - name: cmvol
          configMap:
            name: myindex
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - name: cmvol
            mountPath: /usr/share/nginx/html
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-06-26T20:28:09Z"
    lastUpdateTime: "2022-06-26T20:28:09Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-06-26T20:28:06Z"
    lastUpdateTime: "2022-06-26T20:28:09Z"
    message: ReplicaSet "myweb-8764bf4c8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
