apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: demo9
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: demo9
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - sleep
            - "30"
            image: busybox
            name: demo9
            resources: {}
          restartPolicy: OnFailure
  schedule: 30 * * * *
status: {}
